#!/bin/sh

set -e

alias :=true
changes=0

askyesno () {
	if [ "$DEBIAN_FRONTEND" = "noninteractive" ] ; then
		a=y
		return
	fi

	while : ; do
		echo -n "$1 "
		read a || true
		if [ "$a" = "" ] ; then
			a="y"
		fi
		a=`echo $a | tr A-Z a-z`
		if [ "$a" = "y" ] || [ "$a" = "n" ] ; then
			break
		fi
		echo "Illegal answer"
	done
}

# A cut-down version of 'which' from debianutils.
searchpath () {
	PROGRAM="$1"
	IFS_SAVE="$IFS"
	IFS=:
	RET=1
	for ELEMENT in $PATH; do
		if [ -z "$ELEMENT" ]; then
			ELEMENT=.
		fi
		if [ -f "$ELEMENT/$PROGRAM" ] && \
		   [ -x "$ELEMENT/$PROGRAM" ]; then
			RET=0
			break
		fi
	done
	IFS="$IFS_SAVE"
	return "$RET"
}


if [ ! "$1" = "configure" ] ; then
    exit 0
fi

if [ ! -e $DPKG_SLIND_INSTDIR/etc/passwd ] ; then
	cp $DPKG_SLIND_INSTDIR/usr/share/base-passwd/passwd.master $DPKG_SLIND_INSTDIR/etc/passwd
fi

if [ ! -e $DPKG_SLIND_INSTDIR/etc/group ] ; then
	cp $DPKG_SLIND_INSTDIR/usr/share/base-passwd/group.master $DPKG_SLIND_INSTDIR/etc/group
fi

tmp=`mktemp /tmp/fileXXXXXXXX`

SLIND_UPDATE_PASSWD_OPTIONS="-p $DPKG_SLIND_INSTDIR/usr/share/base-passwd/passwd.master 
			     -g $DPKG_SLIND_INSTDIR/usr/share/base-passwd/group.master
			     -P $DPKG_SLIND_INSTDIR/etc/passwd
			     -S $DPKG_SLIND_INSTDIR/etc/shadow
			     -G $DPKG_SLIND_INSTDIR/etc/group"
if ! update-passwd $SLIND_UPDATE_PASSWD_OPTIONS --dry-run > $tmp ; then
	cat <<EOF

update-passwd has found some differences between your system accounts
and the current Slind defaults. It is advisable to allow update-passwd
to change your system; without those changes some packages might not work
correctly.

The list of proposed changes is:

EOF
	
	cat $tmp
	cat <<EOF

It is highly recommended that you allow update-passwd to make these changes
(a backup file of modified files is made with the extension .org so you can
always restore the current settings).

EOF
	askyesno "May I update your system? [Y/n]"
fi

rm -f $tmp

if [ "$a" = "y" ] ; then
	echo "Okay, I am going to make the necessary updates now"
	update-passwd $SLIND_UPDATE_PASSWD_OPTIONS --verbose || true
	changes=1
elif [ "$a" = "n" ] ; then
	cat <<EOF

Okay, I will not update your system. If you want to make this update later
please check the update-passwd utility.

EOF
fi

# I serously doubt there will be ldap.
#if [ "$changes" -gt 0 ] ; then
#	if searchpath nscd; then
#		nscd -i passwd -i group || true
#	fi
#fi

exit 0

