#! /bin/sh

set -e

if [ ! "$1" = "configure" ] ; then
    exit 0
fi

if [ ! -e /etc/passwd ] ; then
	cp /usr/share/base-passwd/passwd.master /etc/passwd
fi

if [ ! -e /etc/group ] ; then
	cp /usr/share/base-passwd/group.master /etc/group
fi

exit 0
